# -*- coding: utf-8 -*-
"""Flu_Cinate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14c1kXx5gppWtAkxv2HfCWhv2Bg1rt87p
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler, OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin

# Load datasets
train_features = pd.read_csv("training_set_features.csv")
train_labels = pd.read_csv("training_set_labels.csv")
test_features = pd.read_csv("test_set_features.csv")

# display the first 5 rows of the train_features
train_features.head()

# display the first 5 rows of the train_lables
train_labels.head()

# display the first 5 rows of the rest_features
test_features.head()

#print the shape of the datasets
print(train_features.shape)
print(train_labels.shape)
print(test_features.shape)

#print the columns of train_features
train_features.columns

# Merge train_features and train_labels for EDA
train_df = pd.merge(train_features, train_labels, on="respondent_id")
train_df.head()

# check the shape of the merge dataset
print(train_df.shape)

"""## Dataset Shapes summary

  -  training_set_features: 26,707 rows × 36 columns

  - training_set_labels: 26,707 rows × 2 targets + respondent_id

  -  Merged Dataset: 26,707 rows × 38 columns
"""

#check the missing values in descending order
train_df.isnull().sum().sort_values(ascending=False)

# Calculate missing values and percentage
missing_counts = train_df.isnull().sum()
missing_percentage = (missing_counts / len(train_df)) * 100

# Create a summary table for missing data
missing_summary = pd.DataFrame({
    "Missing Values": missing_counts,
    "Missing (%)": missing_percentage
}).sort_values(by="Missing (%)", ascending=False)

missing_summary.head(29)

# Examine dataset structure
dataset_shape = train_df.shape
column_types = train_df.dtypes
missing_values = train_df.isnull().sum()
missing_percentage = (missing_values / len(train_df)) * 100
unique_values = train_df.nunique()

# Create a profile summary DataFrame
profile_summary = pd.DataFrame({
    "Data Type": column_types,
    "Missing Values": missing_values,
    "Missing (%)": missing_percentage,
    "Unique Values": unique_values
})

# Sort the summary
profile_summary = profile_summary.sort_values(
    by=["Missing (%)", "Unique Values"],
    ascending=[False, True]
)

profile_summary.head(29)

"""## Summary

- 50% employment occupation are missiong
- 49% employment industries are missing, followed by health insurance and income povert with 45% and 16% missing values repectively.
"""

# statistical summary for numerical and categorical features
numerical_summary = train_df.describe()
categorical_summary = train_df.describe(include=["O"])

numerical_summary

categorical_summary

# Target variable distribution
target_distribution = train_labels[["h1n1_vaccine", "seasonal_vaccine"]].value_counts().reset_index(name="count")
target_distribution

"""## Demographics & Behavioral Feature summary

  -  Most respondents are White and Female.

  - Largest age group: 65+ Years

  - Top education level: College Graduate

  -  Behaviorally, 82.6% report hand-washing; only 6.9% use face masks.


## Summary of Target variable and class balance

- 13,296 people did not take either vaccine

- 4,697 took both vaccines

- 7,738 took only seasonal

- 977 took only H1N1
---



---

## Key observations:

## Data Size and Structure
- 26,707 respondents
- 38 total columns (36 train_set_features and 3 train_set_labels, joined on the respondent_id)

## Target Variable Distribution
- Evidence of class imbalance: more individuals did not receive either vaccine than those who did
- Importqnt to handle during modelling (e.g, class weighting, resampling techniques)

## Missing Data
- Significant missing values in columns like employment_occupation, employment_industries, health_insurance and income_poverty
- Other missing values scatttered across opinion and behavorial features
## Feature Types
- A mix of numericsl, binary, ordinal and catigorical variables
- Many categorical variables have high cardinality (e.g, employment_occupation with 23 unique values

## Demographic Patterns
- Predominantly 'White and 'Female respondents
- 65+ years is the most represented age group
## Behavorial Patterns
- Most people report handwashing and avioding contact, but fewer use masks or antiviral meds

## Questions & Challenges for Further Investigation
### 1. Which features are most predictive of vaccine uptake?
  - Do beliefs or behaviors have more predictive power than demographics?
### 2. How should we handle missing values?
### 3. Which coulmns should we drop?
### 4. Do patterns differ between H1N1 and seasonal flu vaccination?
  - Can we treat them as separate problems, or are they interdependent?
### 5. How do regional differences (geo or census msa) affect vaccination?
  - Potential geographic disparities in vaccine access or attitudes
### 6. What are the most common combinations of behaviors and outcomes?
  -Are people who wash hands but don’t get vaccinated a significant group?
"""

# Drop specified columns and make a copy
columns_to_drop = ['respondent_id', 'employment_occupation', 'employment_industry']
train_df = train_df.drop(columns=columns_to_drop)
train_df_new = train_df.copy()

train_df_new.head()

train_df_new.columns

# Display structure of the new train_df copy
train_df_new_structure = pd.DataFrame({
    "Column": train_df_new.columns,
    "Data Type": train_df_new.dtypes,
    "Missing Values": train_df_new.isnull().sum(),
    "Missing (%)": (train_df_new.isnull().sum() / len(train_df_new)) * 100
}).reset_index(drop=True)

train_df_new_structure = train_df_new_structure.sort_values(
    by=["Missing (%)", "Missing Values"],
    ascending=[False, False]
)

train_df_new_structure = train_df_new_structure.sort_values(
    by=["Missing (%)", "Missing Values"],
    ascending=[False, False]
)

train_df_new_structure.head()

train_df_new.hhs_geo_region.unique()

# creating a map of region
region_map = {
    'oxchjgsf': 'A',
    'bhuqouqj': 'B',
    'qufhixun': 'C',
    'lrircsnp': 'D',
    'atmpeygn': 'E',
    'lzgpxyit': 'F',
    'fpwskwrf': 'G',
    'mlyzmhmf': 'H',
    'dqpwygqj': 'I',
    'kbazzjca': 'J'
}

train_df_new['hhs_geo_region'] = train_df_new['hhs_geo_region'].map(region_map)

region_map

# Columns to fill with "Unknown"
fill_unknown = [
    "health_insurance",
    "income_poverty",
    "doctor_recc_h1n1",
    "rent_or_own",
    "doctor_recc_seasonal",
    "employment_status",
    "marital_status",
    "education"
]

# Fill specified columns with "Unknown"
for col in fill_unknown:
    if col in train_df_new.columns:
        train_df_new[col] = train_df_new[col].astype(str)
        train_df_new[col].replace("nan", "Unknown", inplace=True)
        train_df_new[col].fillna("Unknown", inplace=True)

# Columns to fill with mode
fill_mode = [
    "chronic_med_condition",
    "child_under_6_months",
    "health_worker",
    "opinion_seas_sick_from_vacc",
    "opinion_seas_risk",
    "opinion_seas_vacc_effective",
    "opinion_h1n1_sick_from_vacc",
    "opinion_h1n1_vacc_effective",
    "opinion_h1n1_risk",
    "household_adults",
    "household_children",
    "behavioral_avoidance",
    "behavioral_touch_face",
    "h1n1_knowledge",
    "h1n1_concern",
    "behavioral_large_gatherings",
    "behavioral_outside_home",
    "behavioral_antiviral_meds",
    "behavioral_wash_hands",
    "behavioral_face_mask"
]

# Fill specified columns with their mode
for col in fill_mode:
    if col in train_df_new.columns:
        mode_value = train_df_new[col].mode()[0]
        train_df_new[col].fillna(mode_value, inplace=True)

# Display the cleaned DataFrame
#display(train_df_new.head())

train_df_new.head()

train_df_new.isnull().sum()

# Make a copy of the imputed dataset to encode
encoded_df = train_df_new.copy()

# Identify categorical columns
cat_cols = encoded_df.select_dtypes(include=['object']).columns.tolist()

# Store label encoders for future use (e.g., test set)
label_encoders = {}

# Apply Label Encoding to all categorical columns
for col in cat_cols:
    le = LabelEncoder()
    encoded_df[col] = le.fit_transform(encoded_df[col])
    label_encoders[col] = le

# Display encoded columns and data types
encoded_info = pd.DataFrame({
    "Column": encoded_df.columns,
    "Data Type": encoded_df.dtypes,
    "Unique Values": [encoded_df[col].nunique() for col in encoded_df.columns]
})

"""## Based on the dataset
- Binary (0 or 1) - like behavorial_avoidance, doctor_recc_h1n1
-Ordinal - like h1n1_concer (0 to 3)
- low range counts - like household_adults and household_children (0 to 3)

most variables have very limited rages and fixed categories
- No continous nemerical columns with high or low values
- Any spreed in values (like 0 -3) is part of the intended response scale

There are no true outliers in this dataset
- No need to remove/transform any data for outliers.


"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plot distribution of H1N1 vaccine
sns.countplot(x='h1n1_vaccine', data=encoded_df, ax=axes[0])
axes[0].set_title('H1N1 Vaccine Distribution')
axes[0].set_xticks([0, 1])
axes[0].set_xticklabels(['Not Vaccinated', 'Vaccinated'])
axes[0].grid()
axes[0].set_ylim(0, 20000)

# Plot distribution of Seasonal vaccine
sns.countplot(x='seasonal_vaccine', data=encoded_df, ax=axes[1])
axes[1].set_title('Seasonal Flu Vaccine Distribution')
axes[1].set_xticks([0, 1])
axes[1].set_xticklabels(['Not Vaccinated', 'Vaccinated'])
axes[1].grid()
axes[1].set_ylim(0, 20000)

# Plot joint distribution (overlap)
overlap = train_df_new.groupby(['h1n1_vaccine', 'seasonal_vaccine']).size().reset_index(name='count')
pivot_table = overlap.pivot(index='h1n1_vaccine', columns='seasonal_vaccine', values='count')
sns.heatmap(pivot_table, annot=True, fmt='d', cmap='Blues', ax=axes[2])
axes[2].set_title('Overlap: H1N1 vs Seasonal Vaccine')
axes[2].set_xlabel('Seasonal Vaccine')
axes[2].set_ylabel('H1N1 Vaccine')



plt.tight_layout()
plt.show()

"""## Summary
## H1N1 Vaccine Distribution
- Majority of respondents did not receive the H1N1 vaccine.

#Seasonal Flu Vaccine Distribution
- More people received the seasonal vaccine compared to H1N1.

#Overlap Heatmap
##Shows how many people fall into each combination of vaccine responses:
  - 4697 people took both vaccines
  - 977 people took h1n1 vaccine
  - 7738 people took the seanal vaccine
  - 13,295 people took either h1n1 vaccine nor the seanoal vaccine

    
"""

train_df.education.unique()

train_df_new.education.unique()

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 1x2 grid for the two plots
fig, axs = plt.subplots(1, 2, figsize=(14, 6))

# --- H1N1 Concern ---
h1n1_concern_counts = encoded_df.groupby(['h1n1_concern', 'h1n1_vaccine']).size().reset_index(name='count')
sns.barplot(
    data=h1n1_concern_counts,
    x='h1n1_concern',
    y='count',
    hue='h1n1_vaccine',
    ax=axs[0]
)
axs[0].set_title('H1N1 Vaccine by Level of Concern')
axs[0].set_xlabel('H1N1 Concern')
axs[0].set_ylabel('Count')

# --- H1N1 Knowledge ---
h1n1_knowledge_counts = encoded_df.groupby(['h1n1_knowledge', 'h1n1_vaccine']).size().reset_index(name='count')
sns.barplot(
    data=h1n1_knowledge_counts,
    x='h1n1_knowledge',
    y='count',
    hue='h1n1_vaccine',
    ax=axs[1]
)
axs[1].set_title('H1N1 Vaccine by Knowledge Level')
axs[1].set_xlabel('H1N1 Knowledge')
axs[1].set_ylabel('Count')

# Set the same y-axis limit for both plots
axs[0].set_ylim(0, 14000)
axs[1].set_ylim(0, 14000)

axs[0].grid()
axs[1].grid()

# Final layout
plt.tight_layout()
plt.show()

print(train_df_new.h1n1_concern.unique())
print()
print(train_df_new.h1n1_knowledge.unique())

"""## Levels of concern about H1N1 ranges 0 = not concerned to 3 = very concerned)
- As concern increases, the number of vaccinated individuals also increases
- The majority of unvaccinated individuals fall in concern levels 1 and 2.
- This suggests a positive relationship between concern and likelihood of getting vaccinated

## Levels of knowledge about H1N1 (0 = no knowledge, 2 = high knowledge)
- People with higher knowledge (level 2) are more likely to be vaccinated.
- Level 1 knowledge has a very large unvaccinated group, but also the highest number of vaccinated individuals.
- Again, this supports the hypothesis that knowledge boosts vaccination likelihood.

both concern and knowledge are important predictors for H1N1 vaccination behavior
"""

# Calculate vaccination rates by education level
education_vaccine_rates = encoded_df.groupby('education',)[['h1n1_vaccine', 'seasonal_vaccine']].mean()

# Plot
education_vaccine_rates.plot(kind='bar', figsize=(10, 6))
plt.title('Vaccination Rates by Education Level')
plt.ylabel('Proportion Vaccinated')
plt.xlabel('Education level')
plt.grid()
plt.xticks(rotation=0)
plt.legend(['H1N1 Vaccine', 'Seasonal Flu Vaccine'])
plt.show()

"""0 = Less than High School

1 = High School

2 = Some College

3 = College Graduate

4 = Postgraduate

- Seasonal flu vaccine uptake were relatively high across all educational levels with highest uptake seen in level 2 (some collage )and 3 (collage graduate)

- H1n1 consistently lower than seasonal flu across all education levels, with peak at some collage level as well.

- Public health awareness for H1N1 may need to be more targeted or widespread across all educational levels.
"""

# Calculate vaccination rates
education_vaccine_rates = encoded_df.groupby('education')[['h1n1_vaccine', 'seasonal_vaccine']].mean()
sex_vaccine_rates = encoded_df.groupby('sex')[['h1n1_vaccine', 'seasonal_vaccine']].mean()
race_vaccine_rates = encoded_df.groupby('race')[['h1n1_vaccine', 'seasonal_vaccine']].mean()

# Create subplots
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Plot: Education
education_vaccine_rates.plot(kind='bar', ax=axes[0])
axes[0].set_title('Vaccination Rates by Education Level')
axes[0].set_ylabel('Proportion Vaccinated')
axes[0].set_xlabel('Education Level')
axes[0].grid()
axes[0].set_xticklabels(education_vaccine_rates.index, rotation=0)
axes[0].legend(['H1N1 Vaccine', 'Seasonal Flu Vaccine'])

# Plot: Sex
sex_vaccine_rates.plot(kind='bar', ax=axes[1])
axes[1].set_title('Vaccination Rates by Sex')
axes[1].set_ylabel('Proportion Vaccinated')
axes[1].set_xlabel('Sex')
axes[1].grid()
axes[1].set_xticklabels(sex_vaccine_rates.index, rotation=0)
axes[1].legend(['H1N1 Vaccine', 'Seasonal Flu Vaccine'])

# Plot: Race
race_vaccine_rates.plot(kind='bar', ax=axes[2])
axes[2].set_title('Vaccination Rates by Race')
axes[2].set_ylabel('Proportion Vaccinated')
axes[2].set_xlabel('Race')
axes[2].grid()
axes[2].set_xticklabels(race_vaccine_rates.index, rotation=45)
axes[2].legend(['H1N1 Vaccine', 'Seasonal Flu Vaccine'])

plt.tight_layout()
plt.show()

print(train_df_new.education.unique())
print(encoded_df.education.unique())
print()
print(train_df_new.sex.unique())
print(encoded_df.sex.unique())
print()
print(train_df_new.race.unique())
print(encoded_df.race.unique())
print()
print(train_df_new.age_group.unique())
print(encoded_df.age_group.unique())
print()
print(train_df_new.rent_or_own.unique())
print(encoded_df.rent_or_own.unique())
print()
print(train_df_new.marital_status.unique())
print(encoded_df.marital_status.unique())
print()
print(train_df_new.employment_status.unique())
print(encoded_df.employment_status.unique())
print()
print(train_df_new.income_poverty.unique())
print(encoded_df.income_poverty.unique())
print()

train_df_new.columns

# Define the demographic features to be analyze
features = ['education','sex','race','age_group', 'income_poverty','rent_or_own', 'marital_status', 'employment_status']
titles = ['Education','sex','Race','Age Group', 'Income Poverty','Rent/Own', 'Marital Status', 'Employment Status']

# Create subplots
fig, axes = plt.subplots(2, 4, figsize=(18, 14))
axes = axes.flatten()  # Flatten the 2x2 grid to iterate easily

# Loop through each feature and plot the vaccination rates
for i, (feature, title) in enumerate(zip(features, titles)):
    vaccine_rates = encoded_df.groupby(feature)[['h1n1_vaccine', 'seasonal_vaccine']].mean()
    vaccine_rates.plot(kind='bar', ax=axes[i])
    axes[i].set_title(f'Vaccination Rates by {title}')
    axes[i].set_ylabel('Proportion Vaccinated')
    axes[i].set_xlabel(title)
    axes[i].grid()
    axes[i].set_ylim(0, 0.7)
    axes[i].set_xticklabels(vaccine_rates.index, rotation=0)
    axes[i].legend(['H1N1 Vaccine', 'Seasonal Flu Vaccine'])

plt.tight_layout()
plt.show()

"""## Vaccination Rate by Education
- vaccinate rates increases with with increase in educational level; especialy for seasonal flu vaccine

## Vaccination Rate by Sex
- seasonal flu rates were higher for both sex, with the highest uptake among females for both vaccine compared to male.

## Vaccination Rate by Race
- among all races, it was obseved that the seasonal vaccine was preferable compare to H1n1 vaccine.
- The white people participated in the vaccine excercise compare other races like black and Hispanic

## Vaccination Rate by Age group
- strong positive correction especially for seasonal flu (increase with increasing age groups)
Older people got vaccinated more

## Vaccination Rate by income poverty
- Higher income groups are more likely to be vaccinated, for both vaccines.

## Vaccination Rate by Rent or Own
- Those who own homes have much higher vaccination rates

## Vaccination Rate by Marital Status
- Married people tend to get vaccinated more — possibly due to family influence

## Vaccination Rate by Education Status
- people who are not in the labor force got more seasonal flu vaccination followed by people who are enployed.
- equal proportion of people who are not in the labor force and employed got h1n1 vaccine
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure with 2 rows and 3 columns of subplots
fig, axs = plt.subplots(2, 3, figsize=(18, 10))

# ---------------------------
# Top row: H1N1 vaccine opinions
# ---------------------------
# Plot H1N1 Vaccine vs Opinion: Effectiveness
sns.countplot(
    data=train_df_new,
    x='opinion_h1n1_vacc_effective',
    hue='h1n1_vaccine',
    ax=axs[0, 0]
)
axs[0, 0].set_ylabel('Count')
axs[0, 0].set_xlabel('H1N1 Effective Opinion')
axs[0, 0].set_title('H1N1 Vaccine by Effectiveness Opinion')
axs[0, 0].grid()
axs[0, 0].set_ylim(0, 12000)

# Plot H1N1 Vaccine vs Opinion: Risk
sns.countplot(
    data=train_df_new,
    x='opinion_h1n1_risk',
    hue='h1n1_vaccine',
    ax=axs[0, 1]
)
axs[0, 1].set_ylabel('Count')
axs[0, 1].set_xlabel('H1N1 Risk Opinion')
axs[0, 1].set_title('H1N1 Vaccine by Risk Opinion')
axs[0, 1].grid()
axs[0, 1].set_ylim(0, 12000)

# Plot H1N1 Vaccine vs Opinion: Sick from Vaccination
sns.countplot(
    data=train_df_new,
    x='opinion_h1n1_sick_from_vacc',
    hue='h1n1_vaccine',
    ax=axs[0, 2]
)
axs[0, 2].set_ylabel('Count')
axs[0, 2].set_xlabel('H1N1 Sick-from-Vaccine Opinion')
axs[0, 2].set_title('H1N1 Vaccine by Sick-from-Vacc Opinion')
axs[0, 2].grid()
axs[0, 2].set_ylim(0, 12000)

# ---------------------------
# Bottom row: Seasonal vaccine opinions
# ---------------------------
# Plot Seasonal Vaccine vs Opinion: Effectiveness
sns.countplot(
    data=train_df_new,
    x='opinion_seas_vacc_effective',
    hue='seasonal_vaccine',
    ax=axs[1, 0]
)
axs[1, 0].set_ylabel('Count')
axs[1, 0].set_xlabel('Seasonal Vaccine Effective Opinion')
axs[1, 0].set_title('Seasonal Vaccine by Effectiveness Opinion')
axs[1, 0].grid()
axs[1, 0].set_ylim(0, 12000)

# Plot Seasonal Vaccine vs Opinion: Risk
sns.countplot(
    data=train_df_new,
    x='opinion_seas_risk',
    hue='seasonal_vaccine',
    ax=axs[1, 1]
)
axs[1, 1].set_ylabel('Count')
axs[1, 1].set_xlabel('Seasonal Vaccine Risk Opinion')
axs[1, 1].set_title('Seasonal Vaccine by Risk Opinion')
axs[1, 1].grid()
axs[1, 1].set_ylim(0, 12000)

# Plot Seasonal Vaccine vs Opinion: Sick from Vaccination
sns.countplot(
    data=train_df_new,
    x='opinion_seas_sick_from_vacc',
    hue='seasonal_vaccine',
    ax=axs[1, 2]
)
axs[1, 2].set_ylabel('Count')
axs[1, 2].set_xlabel('Seasonal Vaccine Sick-from-Vaccine Opinion')
axs[1, 2].set_title('Seasonal Vaccine by Sick-from-Vacc Opinion')
axs[1, 2].grid()
axs[1, 2].set_ylim(0, 12000)

# Improve layout and display the plots
plt.tight_layout()
plt.show()

"""## Level of opinion (from 1 to 5 — likely “Strongly Disagree” to “Strongly Agree”)

## H1n1 Effectiveness Opinion
- As belief in the effectiveness increases (1- 5) vaccinatin also increases
- Especially for the Seasonal Flu, a huge number of people who rated effectiveness as 5 got vaccinated.
. people are skeptical about vaccine effectiveness (rating 1 or 2) mostly did not get vaccinated.

## H1n1 Risk Opinion
- low perceived risk (1 -2) correlated with low vaccination rates
- People who felt at higher risk (rating 4–5) were more likely to vaccinate.
- Seasonal flu vaccine uptake is especially higher among people who feel at moderate-to-high risk

## H1n1 Sick-from-VAccine Opinion
- People who believe the vaccine will make them sick are less likely to vaccinate.

- For the seasonal vaccine, a higher number of people who do not believe tzat they will get sick got vaccinated.
"""

print(train_df_new.opinion_h1n1_vacc_effective.unique())
print(encoded_df.opinion_h1n1_vacc_effective.unique())
print()
print(train_df_new.opinion_h1n1_risk.unique())
print(encoded_df.opinion_h1n1_risk.unique())
print()
print(train_df_new.opinion_h1n1_sick_from_vacc.unique())
print(encoded_df.opinion_h1n1_sick_from_vacc.unique())
print()
print(train_df_new.opinion_seas_vacc_effective.unique())
print(encoded_df.opinion_seas_vacc_effective.unique())
print()
print(train_df_new.opinion_seas_risk.unique())
print(encoded_df.opinion_seas_risk.unique())
print()
print(train_df_new.opinion_seas_sick_from_vacc.unique())
print(encoded_df.opinion_seas_sick_from_vacc.unique())

# Create a figure with 2 rows and 3 columns of subplots
fig, axs = plt.subplots(2, 3, figsize=(18, 10))

# ---------------------------
# Top row: H1N1 vaccine opinions (count vs opinion, hue by race)
# ---------------------------

# H1N1 Vaccine vs Opinion: Effectiveness
sns.countplot(
    data=encoded_df,
    x='opinion_h1n1_vacc_effective',
    hue='race',
    ax=axs[0, 0]
)
axs[0, 0].set_ylabel('Count')
axs[0, 0].set_xlabel('H1N1 Vaccine Effectiveness Opinion')
axs[0, 0].set_title('H1N1 Vaccine: Effectiveness Opinion by Race')
axs[0, 0].grid()
axs[0, 0].set_ylim(0, 12000)

# H1N1 Vaccine vs Opinion: Risk
sns.countplot(
    data=encoded_df,
    x='opinion_h1n1_risk',
    hue='race',
    ax=axs[0, 1]
)
axs[0, 1].set_ylabel('Count')
axs[0, 1].set_xlabel('H1N1 Risk Opinion')
axs[0, 1].set_title('H1N1 Vaccine: Risk Opinion by Race')
axs[0, 1].grid()
axs[0, 1].set_ylim(0, 12000)

# H1N1 Vaccine vs Opinion: Sick from Vaccination
sns.countplot(
    data=encoded_df,
    x='opinion_h1n1_sick_from_vacc',
    hue='race',
    ax=axs[0, 2]
)
axs[0, 2].set_ylabel('Count')
axs[0, 2].set_xlabel('H1N1 Sick-from-Vaccine Opinion')
axs[0, 2].set_title('H1N1 Vaccine: Sick-from-Vaccine Opinion by Race')
axs[0, 2].grid()
axs[0, 2].set_ylim(0, 12000)

# ---------------------------
# Bottom row: Seasonal vaccine opinions
# ---------------------------

# Seasonal Vaccine vs Opinion: Effectiveness
sns.countplot(
    data=encoded_df,
    x='opinion_seas_vacc_effective',
    hue='race',
    ax=axs[1, 0]
)
axs[1, 0].set_ylabel('Count')
axs[1, 0].set_xlabel('Seasonal Vaccine Effectiveness Opinion')
axs[1, 0].set_title('Seasonal Vaccine: Effectiveness Opinion by Race')
axs[1, 0].grid()
axs[1, 0].set_ylim(0, 12000)

# Seasonal Vaccine vs Opinion: Risk
sns.countplot(
    data=encoded_df,
    x='opinion_seas_risk',
    hue='race',
    ax=axs[1, 1]
)
axs[1, 1].set_ylabel('Count')
axs[1, 1].set_xlabel('Seasonal Vaccine Risk Opinion')
axs[1, 1].set_title('Seasonal Vaccine: Risk Opinion by Race')
axs[1, 1].grid()
axs[1, 1].set_ylim(0, 12000)

# Seasonal Vaccine vs Opinion: Sick from Vaccination
sns.countplot(
    data=encoded_df,
    x='opinion_seas_sick_from_vacc',
    hue='race',
    ax=axs[1, 2]
)
axs[1, 2].set_ylabel('Count')
axs[1, 2].set_xlabel('Seasonal Vaccine Sick-from-Vaccine Opinion')
axs[1, 2].set_title('Seasonal Vaccine: Sick-from-Vaccine Opinion by Race')
axs[1, 2].grid()
axs[1, 2].set_ylim(0, 12000)

# Improve layout and display the plots
plt.tight_layout()
plt.show()

"""## Effectiveness Opinion by Race
- In both H1n1 and seasonal flu vaccine, white race dominates among all races who believe/strogly believe on vaccine effecitiveness.
- races (0 -2) are present in lower numbers across all levels.
- this suggests that people in white are more likely to believe in vaccine effectiveness.

## Risk Opinion by Race
- Race 3 (white )is most frequent and is spread across all risk levels. peaking at 2, compared to other races (0-2)
- other races do not perceive high personal risk.

## Sick-from-Vaccine Opinion by Race
- For both vaccines, Race 3 (white) has the highest number of people believing they won’t get sick from the vaccine (rating 1–2).
- other races showed that they maybe skeptical or incertain about the side effects.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure with 2 rows and 1 column of subplots
fig, axs = plt.subplots(2, 1, figsize=(14, 10))

# -------------------------------
# Plot H1N1 Vaccine by Health Insurance and Age Group
# -------------------------------
sns.countplot(
    data=train_df_new,
    x='health_insurance',
    hue='h1n1_vaccine',
    ax=axs[0]
)
axs[0].set_title('H1N1 Vaccine Count by Health Insurance')
axs[0].set_xlabel('Health Insurance')
axs[0].set_ylabel('Number of Respondents')
axs[0].grid()
axs[0].set_ylim(0, 12000)


# Optional: Add age_group grouping (use barplot if you want more control, or split plots)

# -------------------------------
# Plot Seasonal Vaccine by Health Insurance and Age Group
# -------------------------------
sns.countplot(
    data=train_df_new,
    x='health_insurance',
    hue='seasonal_vaccine',
    ax=axs[1]
)
axs[1].set_title('Seasonal Vaccine Count by Health Insurance')
axs[1].set_xlabel('Health Insurance')
axs[1].set_ylabel('Number of Respondents')
axs[1].grid()
axs[1].set_ylim(0, 12000)

# Improve layout and display the plots
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure with 2 rows and 1 column of subplots
fig, axs = plt.subplots(2, 1, figsize=(14, 10))

# -------------------------------
# Plot H1N1 Vaccine by Health Insurance and Age Group
# -------------------------------
sns.countplot(
    data=encoded_df,
    x='health_insurance',
    hue='h1n1_vaccine',
    ax=axs[0]
)
axs[0].set_title('H1N1 Vaccine Count by Health Insurance')
axs[0].set_xlabel('Health Insurance')
axs[0].set_ylabel('Number of Respondents')
axs[0].grid()
axs[0].set_ylim(0, 12000)


# Optional: Add age_group grouping (use barplot if you want more control, or split plots)

# -------------------------------
# Plot Seasonal Vaccine by Health Insurance and Age Group
# -------------------------------
sns.countplot(
    data=encoded_df,
    x='health_insurance',
    hue='seasonal_vaccine',
    ax=axs[1]
)
axs[1].set_title('Seasonal Vaccine Count by Health Insurance')
axs[1].set_xlabel('Health Insurance')
axs[1].set_ylabel('Number of Respondents')
axs[1].grid()
axs[1].set_ylim(0, 12000)


# Improve layout and display the plots
plt.tight_layout()
plt.show()

"""## Health Insurance Coding:

  - 0 = No insurance

  - 1 = Has insurance

  - 2 = Unknown / Not reported

- Respondents with insurance (1) had significantly higher vaccination rates compared to those without insurance (0).

- The unknown (2) shows the highest number of respondents, but they are largely unvaccinated.
- for seansonal vaccine, among those with insurance (1), vaccination numbers slightly surpass non-vaccination, unlike H1N1.
. The uninsured (0) shows very low vaccination uptake.
    
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure with 2 rows and 4 columns of subplots
fig, axs = plt.subplots(2, 4, figsize=(22, 12))

# Plot H1N1 Vaccine counts
sns.countplot(
    data=encoded_df,
    x='doctor_recc_h1n1',
    hue='h1n1_vaccine',
    ax=axs[0, 0]
)
axs[0, 0].set_xlabel('Doctor Recommendation')
axs[0, 0].set_ylabel('Count')
axs[0, 0].set_title('H1N1 Vaccine by Doctor Recommendation')
axs[0, 0].grid()
axs[0, 0].set_ylim(0, 20000)


sns.countplot(
    data=encoded_df,
    x='health_worker',
    hue='h1n1_vaccine',
    ax=axs[0, 1]
)
axs[0, 1].set_xlabel('Health Worker')
axs[0, 1].set_ylabel('Count')
axs[0, 1].set_title('H1N1 Vaccine by Health Worker')
axs[0, 1].grid()
axs[0, 1].set_ylim(0, 20000)

sns.countplot(
    data=encoded_df,
    x='child_under_6_months',
    hue='h1n1_vaccine',
    ax=axs[0, 2]
)
axs[0, 2].set_xlabel('Child Under 6 Months')
axs[0, 2].set_ylabel('Count')
axs[0, 2].set_title('H1N1 Vaccine by Child Under 6 Months')
axs[0, 2].grid()
axs[0, 2].set_ylim(0, 20000)

sns.countplot(
    data=encoded_df,
    x='chronic_med_condition',
    hue='h1n1_vaccine',
    ax=axs[0, 3]
)
axs[0, 3].set_xlabel('Chronic Medical Condition')
axs[0, 3].set_ylabel('Count')
axs[0, 3].set_title('H1N1 Vaccine by Chronic Medical Condition')
axs[0, 3].grid()
axs[0, 3].set_ylim(0, 20000)

# Plot Seasonal Vaccine counts
sns.countplot(
    data=encoded_df,
    x='doctor_recc_seasonal',
    hue='seasonal_vaccine',
    ax=axs[1, 0]
)
axs[1, 0].set_xlabel('Doctor Recommendation')
axs[1, 0].set_ylabel('Count')
axs[1, 0].set_title('Seasonal Vaccine by Doctor Recommendation')
axs[1, 0].grid()
axs[1, 0].set_ylim(0, 20000)

sns.countplot(
    data=encoded_df,
    x='health_worker',
    hue='seasonal_vaccine',
    ax=axs[1, 1]
)
axs[1, 1].set_xlabel('Health Worker')
axs[1, 1].set_ylabel('Count')
axs[1, 1].set_title('Seasonal Vaccine by Health Worker')
axs[1, 1].grid()
axs[1, 1].set_ylim(0, 20000)

sns.countplot(
    data=encoded_df,
    x='child_under_6_months',
    hue='seasonal_vaccine',
    ax=axs[1, 2]
)
axs[1, 2].set_xlabel('Child Under 6 Months')
axs[1, 2].set_ylabel('Count')
axs[1, 2].set_title('Seasonal Vaccine by Child Under 6 Months')
axs[1, 2].grid()
axs[1, 2].set_ylim(0, 20000)

sns.countplot(
    data=encoded_df,
    x='chronic_med_condition',
    hue='seasonal_vaccine',
    ax=axs[1, 3]
)
axs[1, 3].set_xlabel('Chronic Medical Condition')
axs[1, 3].set_ylabel('Count')
axs[1, 3].set_title('Seasonal Vaccine by Chronic Medical Condition')
axs[1, 3].grid()
axs[1, 3].set_ylim(0, 20000)

# Tidy layout
plt.tight_layout()
plt.show()

"""## Doctor Recommendation
- Doctor's recommendation shows a clear impact on both H1N1 and seasonal vaccination rates.
- Among those who received a recommendation, much more got vaccinated.

##  Health Worker Status
- Among people who are not health workers, much people did not receive vaccination compared to peaploe who receieved.
- for seasonal flu vaccine, among health workers, more peaple got vaccinated.

## Presence of a Child < 6 Months
- Households with a child under 6 months show lower vaccination rates, especially for H1N1.
- almost equal rates for seasonal flu vaccine.

## Chronic Medical Condition
- for seasonal flu vaccine, individuals with chronic conditions (1) got more vaccinated unlike H1n1 vaccine
"""

print(train_df_new.doctor_recc_h1n1.unique())
print(encoded_df.doctor_recc_h1n1.unique())
print()
print(train_df_new.doctor_recc_seasonal.unique())
print(encoded_df.doctor_recc_seasonal.unique())
print()
print(train_df_new.health_worker.unique())
print(encoded_df.health_worker.unique())
print()
print(train_df_new.child_under_6_months.unique())
print(encoded_df.child_under_6_months.unique())
print()
print(train_df_new.chronic_med_condition.unique())
print(encoded_df.chronic_med_condition.unique())

# Create a figure with 2 rows and 4 columns of subplots
fig, axs = plt.subplots(2, 4, figsize=(22, 12))

# H1N1 Vaccine: filter only those who received it (==1)
h1n1_vaccinated = encoded_df[encoded_df['h1n1_vaccine'] == 1]

sns.countplot(
    data=h1n1_vaccinated,
    x='doctor_recc_h1n1',
    hue='age_group',
    ax=axs[0, 0]
)
axs[0, 0].set_xlabel('Doctor Recommendation')
axs[0, 0].set_ylabel('Count')
axs[0, 0].set_title('H1N1 Vaccinated by Doctor Recommendation & Age')
axs[0, 0].grid()
axs[0, 0].set_ylim(0, 6000)

sns.countplot(
    data=h1n1_vaccinated,
    x='health_worker',
    hue='age_group',
    ax=axs[0, 1]
)
axs[0, 1].set_xlabel('Health Worker')
axs[0, 1].set_ylabel('Count')
axs[0, 1].set_title('H1N1 Vaccinated by Health Worker & Age')
axs[0, 1].grid()
axs[0, 1].set_ylim(0, 6000)

sns.countplot(
    data=h1n1_vaccinated,
    x='child_under_6_months',
    hue='age_group',
    ax=axs[0, 2]
)
axs[0, 2].set_xlabel('Child Under 6 Months')
axs[0, 2].set_ylabel('Count')
axs[0, 2].set_title('H1N1 Vaccinated by Child <6 Months & Age')
axs[0, 2].grid()
axs[0, 2].set_ylim(0, 6000)

sns.countplot(
    data=h1n1_vaccinated,
    x='chronic_med_condition',
    hue='age_group',
    ax=axs[0, 3]
)
axs[0, 3].set_xlabel('Chronic Medical Condition')
axs[0, 3].set_ylabel('Count')
axs[0, 3].set_title('H1N1 Vaccinated by Chronic Illness & Age')
axs[0, 3].grid()
axs[0, 3].set_ylim(0, 6000)

# Seasonal Vaccine: filter only those who received it (==1)
seasonal_vaccinated = encoded_df[encoded_df['seasonal_vaccine'] == 1]

sns.countplot(
    data=seasonal_vaccinated,
    x='doctor_recc_seasonal',
    hue='age_group',
    ax=axs[1, 0]
)
axs[1, 0].set_xlabel('Doctor Recommendation')
axs[1, 0].set_ylabel('Count')
axs[1, 0].set_title('Seasonal Vaccinated by Doctor Recommendation & Age')
axs[1, 0].grid()
axs[1, 0].set_ylim(0, 6000)

sns.countplot(
    data=seasonal_vaccinated,
    x='health_worker',
    hue='age_group',
    ax=axs[1, 1]
)
axs[1, 1].set_xlabel('Health Worker')
axs[1, 1].set_ylabel('Count')
axs[1, 1].set_title('Seasonal Vaccinated by Health Worker & Age')
axs[1, 1].grid()
axs[1, 1].set_ylim(0, 6000)

sns.countplot(
    data=seasonal_vaccinated,
    x='child_under_6_months',
    hue='age_group',
    ax=axs[1, 2]
)
axs[1, 2].set_xlabel('Child Under 6 Months')
axs[1, 2].set_ylabel('Count')
axs[1, 2].set_title('Seasonal Vaccinated by Child <6 Months & Age')
axs[1, 2].grid()
axs[1, 2].set_ylim(0, 6000)

sns.countplot(
    data=seasonal_vaccinated,
    x='chronic_med_condition',
    hue='age_group',
    ax=axs[1, 3]
)
axs[1, 3].set_xlabel('Chronic Medical Condition')
axs[1, 3].set_ylabel('Count')
axs[1, 3].set_title('Seasonal Vaccinated by Chronic Illness & Age')
axs[1, 3].grid()
axs[1, 3].set_ylim(0, 6000)

# Final layout
plt.tight_layout()
plt.show()

"""## Doctor Recommendation:

- A strong recommendation significantly increases vaccination rates across all age groups, but especially for older adults.
- based on doczores recommendations, Seasonal vaccine rates is generally higher compared to H1N1,  more especially in older age groups who more likely to be at risk of infection.

## Health Worker Status
- vaccination among health workers shows a sharp age-gradient effect; with older active health workers getting vaccinated.
- 65+ yeras dominated among people who are not health workers

## Child Under 6 Months
The presence of a child seems to slightly increase vaccine uptake, but the effect is modest overall unlike household without the presence of a child.

## Chronic Illness
- people with chronic illnesses (1), particularly those in older age groups, are much more likely to vaccinate.
- effect is stronger for seasonal flu, but present in H1N1 as well.
"""

# Filter for people who took either vaccine
vaccinated_df = train_df_new[(train_df_new['h1n1_vaccine'] == 1) | (train_df_new['seasonal_vaccine'] == 1)]

# Melt the dataframe to long format
vaccinated_long = pd.melt(
    vaccinated_df,
    id_vars=['hhs_geo_region'],
    value_vars=['h1n1_vaccine', 'seasonal_vaccine'],
    var_name='vaccine_type',
    value_name='status'
)

# Keep only rows where status == 1 (vaccinated)
vaccinated_long = vaccinated_long[vaccinated_long['status'] == 1]

# Create the count plot
plt.figure(figsize=(14, 6))
sns.countplot(
    data=vaccinated_long,
    x='hhs_geo_region',
    hue='vaccine_type',
    order=sorted(vaccinated_long['hhs_geo_region'].unique())
)

plt.title('Count of Vaccinated Individuals by HHS Geo Region and Vaccine Type')
plt.xlabel('HHS Geo Region')
plt.ylabel('Count')
plt.legend(title='Vaccine Type', labels=['H1N1 Vaccine', 'Seasonal Vaccine'])
plt.grid()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Seasonal Vaccine
- Region F stands out with the highest proportion of people who got vaccinated.

Regions A, B, C, G, and J also have strong vaccination counts.

Region I shows the lowest vaccine rates.

## H1N1 Vaccine
- Lower proportion allover compared to the seasonal vaccine
- Region F again dominates with the most vaccinations rate.  
- Region I is also lowest vaccination behavoiur
"""

# Filter for people who took either vaccine
vaccinated_df = train_df_new[(train_df_new['h1n1_vaccine'] == 1) | (train_df_new['seasonal_vaccine'] == 1)]

# Melt the dataframe to long format
vaccinated_long = pd.melt(
    vaccinated_df,
    id_vars=['hhs_geo_region', 'census_msa'],
    value_vars=['h1n1_vaccine', 'seasonal_vaccine'],
    var_name='vaccine_type',
    value_name='status'
)

# Keep only rows where status == 1 (vaccinated)
vaccinated_long = vaccinated_long[vaccinated_long['status'] == 1]

# Create the count plot with census_msa as an additional facet (e.g., columns)
g = sns.catplot(
    data=vaccinated_long,
    x='hhs_geo_region',
    hue='vaccine_type',
    col='census_msa',
    kind='count',
    col_wrap=3,
    order=sorted(vaccinated_long['hhs_geo_region'].unique()),
    height=5,
    aspect=1.2
)

g.set_titles(col_template="{col_name}")
g.set_axis_labels("HHS Geo Region", "Count")
g.set_xticklabels(rotation=45)
g._legend.set_title("Vaccine Type")
g._legend.set_frame_on(True)
g.set_titles("Census MSA: {col_name}")
plt.subplots_adjust(top=0.9)
g.fig.suptitle('Vaccination Counts by HHS Geo Region, Vaccine Type, and Census MSA')

for ax in g.axes.flat:
    ax.grid(True)

plt.show()

"""This grouped bar chart displays vaccination counts for both the H1N1 and seasonal flu vaccines across:

HHS Geo Regions (A–J),

Split by Census MSA types:

- Non-MSA (rural areas),

- MSA, Not Principle City (urban/suburban outskirts),

- MSA, Principle City (urban centers).

## More Seasonal Vaccine uptake comapred to H1N1 Vaccine
Across all regions and MSA types, the seasonal vaccine consistently has higher counts than the H1N1 vaccine — suggesting it was more widely accepted or better distributed.

## Urban-Rural Divide
- MSA (urban/suburban areas) generally show higher vaccination counts for both vaccines.

- Non-MSA (rural) areas show lower uptake, especially stark for H1N1.

  - Possibly due to access barriers or lower perceived risk.

## Regional Differences
- Region F (MSA, Not Principle City) had the highest seasonal vaccination count overall.

- Region I consistently has very low counts, regardless of MSA status

## Why This Matters
This chart reveals that vaccination behavior varies not just by individual beliefs, but also by geographic and urbanization context. These patterns suggest:

- Targeted regional or rural interventions may be effective.

- Rural areas may need access and outreach programs.
"""

# Compute correlation matrix
behavioral_cols = ['behavioral_antiviral_meds', 'behavioral_avoidance', 'behavioral_face_mask',
                   'behavioral_wash_hands', 'behavioral_large_gatherings', 'behavioral_outside_home',
                   'behavioral_touch_face']

correlation_matrix = train_df_new[behavioral_cols].corr(method='spearman')  # Spearman for ordinal/categorical data
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Behavioral Variables Correlation Matrix')
plt.show()

"""## Correlated Behaviors:

- behavioral_large_gatherings & behavioral_outside_home: 0.58
    - Makes intuitive sense—people going out are more likely to be in large gatherings.

- behavioral_touch_face & behavioral_wash_hands: 0.36
    - Possibly suggests that people who recognize risky behavior (like touching face) are also washing hands more.

- behavioral_avoidance & behavioral_wash_hands / touch_face: ~0.33
    - Avoidance aligns moderately with hygiene-related behavior.

- behavioral_antiviral_meds has low correlations with all others (~0.05–0.15)
    - Suggests this variable is independent of general behaviorial patterns; perhaps driven by specific health conditions or doctor prescriptions.

"""

# feature analysis
# Compute the correlation matrix
corr_matrix = encoded_df.corr()

# Plot heatmap with hierarchical clustering
sns.set(style="white")
plt.figure(figsize=(20, 18))
sns.clustermap(
    corr_matrix,
    cmap="coolwarm",
    method="ward",
    metric="euclidean",
    linewidths=0.5,
    figsize=(20, 20)
)
plt.title("Correlation Heatmap with Hierarchical Clustering", y=1.05)
plt.show()

"""Each square of the heatmap shows the correlation coefficient (ranging from -1 to +1) between a pair of variables.

- Red = Strong positive correlation (e.g., variables increase together)

- Blue = Strong negative correlation (e.g., one increases while the other decreases)

- White/Light = Weak or no

## Hierarchical Clustering
The tree structures on the top and left group similar variables together based on their correlation patterns.
- This helps identify clusters of related features — useful for understanding redundancy.

## Key Observation
Clusters of Interest
- Vaccine-related opinions and concerns (e.g., opinion_h1n1_risk, opinion_h1n1_vacc_effective, h1n1_concern) are closely clustered and positively correlated — expected, as these variables often influence each other.

- Doctor recommendations (doctor_recc_h1n1, doctor_recc_seasonal) are strongly correlated with vaccine uptake.

- Behavioral variables (like behavioral_wash_hands, behavioral_avoidance) form another cluster, likely reflecting general caution or health-conscious behavior.

Redundant Pairs
- Features like opinion_h1n1_risk and opinion_h1n1_vacc_effective show strong correlation — may carry overlapping information.

- Similarly, household_adults and household_children. Maybe grouped as (family size structure) for feature reduction if highly correlated numerically.

Why This Matters for Modeling?
- Reduce redundancy

- Prevent multicollinearity

- Speed up training
"""

# Set correlation threshold for redundancy
threshold = 0.9

# Compute absolute correlation matrix
corr_matrix = encoded_df.corr().abs()

# Select upper triangle of the correlation matrix (to avoid duplicate pairs)
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find feature pairs with correlation above threshold
redundant_pairs = [
    (column, row, upper.loc[row, column])
    for column in upper.columns
    for row in upper.index
    if pd.notnull(upper.loc[row, column]) and upper.loc[row, column] >= threshold
]

# Sort pairs by correlation strength
redundant_pairs_sorted = sorted(redundant_pairs, key=lambda x: -x[2])

# Display top redundant feature pairs
for f1, f2, corr in redundant_pairs_sorted:
    print(f"{f1} and {f2} → correlation = {corr:.3f}")

# Create a new feature: total household size
encoded_df['household_size'] = encoded_df['household_adults'] + encoded_df['household_children']

encoded_df.drop(columns=['household_adults', 'household_children'], inplace=True)

# Set of features to drop
features_to_drop = set()

for f1, f2, _ in redundant_pairs_sorted:
    if f1 not in features_to_drop and f2 not in features_to_drop:
        features_to_drop.add(f2)  # Drop the second one (could be any logic)

# Drop from dataset
encoded_df_reduced = encoded_df.drop(columns=list(features_to_drop))

# calssify using randomForestclassifier
from sklearn.ensemble import RandomForestClassifier

def get_feature_importance(df, target_col):
    X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
    y = df[target_col]

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)

    importances = model.feature_importances_
    feature_names = X.columns

    importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importances
    }).sort_values(by='Importance', ascending=False)

    return importance_df

# Get importance rankings
h1n1_importance = get_feature_importance(encoded_df, 'h1n1_vaccine')
seasonal_importance = get_feature_importance(encoded_df, 'seasonal_vaccine')

h1n1_importance

seasonal_importance

# Merge top features from both targets
merged_importance = pd.merge(
    h1n1_importance.head(15).rename(columns={'Importance': 'H1N1_Importance'}),
    seasonal_importance.head(15).rename(columns={'Importance': 'Seasonal_Importance'}),
    on='Feature',
    how='outer'
).fillna(0)

# Show comparison
print(merged_importance.sort_values(by=['H1N1_Importance', 'Seasonal_Importance'], ascending=False))

import matplotlib.pyplot as plt

# Horizontal bar plot
merged_importance.set_index('Feature').plot(
    kind='barh',
    figsize=(12, 8),
    title='Top Feature Importance Comparison: H1N1 vs Seasonal Flu'
)
plt.xlabel("Importance Score")
plt.tight_layout()
plt.grid()
plt.gca().invert_yaxis()
plt.show()

"""Each feature has two bars:

- Blue: Importance for predicting H1N1 vaccination

- Orange: Importance for predicting Seasonal flu vaccination

The longer the bar, the more influence that feature had in the model's prediction.

- Doctor recommendations (doctor_recc_h1n1 and doctor_recc_seasonal) were highly important for both vaccines — showing that medical advice is a strong behavioral driver.

- Risk perception and vaccine effectiveness beliefs are very influential for both cases.

## Unexpected or Counterintuitive
- Demographics like income_poverty and education had low importance, which might be surprising — possibly indicating that personal beliefs matter more than socioeconomics.

- household_adults had some influence on seasonal flu uptake, but little to none on H1N1.
"""



"""## Document Insights About Influential Factors
## Summary of Key Findings
# From Correlation Analysis

A number of features exhibit high pairwise correlations (≥ 0.9), indicating potential redundancy.

Example redundant pairs identified:

- household_adults and household_children — typically reflect family structure and may be tightly coupled.

- opinion_h1n1_vacc_effective and opinion_h1n1_risk — suggest people who believe the vaccine is effective also perceive high risk from H1N1.

Highly correlated features may introduce multicollinearity, which can skew model interpretability. Reducing such redundancy is a good pre-modeling step.
"""



"""## From Random Forest Feature Importance (H1N1 vs Seasonal Flu)
Top Features for H1N1 Vaccine:
- opinion_h1n1_risk — perceived risk strongly predicts H1N1 vaccine uptake.

- opinion_h1n1_vacc_effective — belief in effectiveness is key.

- age_group — older age groups more likely to take H1N1 vaccine.

- doctor_recc_h1n1 — strong indicator; medical recommendation influences uptake.

- chronic_med_condition — people with pre-existing conditions may seek protection.

Top Features for Seasonal Flu Vaccine:
- opinion_seas_vacc_effective — belief in effectiveness influences seasonal flu uptake.

- doctor_recc_seasonal — strong predictor for seasonal flu vaccination.

- health_worker — likely to get vaccinated due to occupational exposure.

- age_group — similar influence as with H1N1.

- opinion_seas_risk — perceived risk drives decision-making.

## Unexpected or Counterintuitive Relationships
- Education level had less importance than expected — one might assume higher education correlates with vaccine uptake, but it didn’t dominate.

- Health insurance and income_poverty didn’t consistently rank high — though intuitively linked to access and decision-making, other psychosocial or belief-based features had stronger predictive power.

- Behavioral features like behavioral_antiviral_meds had moderate influence — indicating that past health behaviors don’t always directly translate to vaccination behavior.
"""



"""## Implications for Modeling
- Belief and perception-based features (like opinions and perceived risk) are more influential than many demographic variables.

- Medical recommendation is a consistently strong predictor — highlighting the role of trusted authorities in health decisions.

- For modeling and feature selection:

  - Consider keeping the top 10–15 features from each target for a lean model.

  - Address high-correlation pairs by dropping one feature from each pair.
"""



"""## EDA Report Compilation
- The exploratory data analysis (EDA) revealed that beliefs about vaccine effectiveness and risk perception, along with doctor recommendations, are the strongest predictors of whether a person received the H1N1 or seasonal flu vaccine.

- While some demographic factors like age group played a moderate role, others like education and income level were less influential than expected. Several features were found to be highly correlated, indicating potential redundancy to address during modeling.

- These insights would serve as guide for feature selection, model development, and visualization, aligning closely with the project’s goal to understand and predict vaccination behavior effectively.
"""